# Single spline file for all recordings (True) or one for each recording
# (False).
single_spline_file: False

# Only one of the following will be in use.
# If a single spline file, what is it called.
spline_file:
# If not a single spline, what glob pattern should be used to find the splines.
# E.g. '*.csv'
spline_file_glob: '*.csv'

# Do the files have a header row?
# Please note that possible header row information is ignored.
headers: True

# Either 'polar' or 'Cartesian' 
coordinates: polar

# Are the coordinates interleaved in 
#  interleaved format (True): point1/x point1/y point2/x point2/y
#  or non-interleaved (False): point1/x point2/x ... point1/y point2/y
interleaved_coords: False

# These are listed in order of appearance in the file. 
# Please note that possible header row information is ignored.
# Accepted values:
  # - ignore: marks a column to be ignored, unlike the others below, 
  #   can be used several times
  # - id: used to identify the speaker, 
  #   often contained in a csv field called 'family name'
  # - given names: appended to 'id' if not marked 'ignore'
  # - date and time: dat3 and time of recording
  # - prompt: prompt of recording, used to identify the recording with 'id'
  # - annotation label: optional field containing annotation information
  # - time in recording: timestamp of the frame this spline belongs to
  # - number of spline points: number of sample points in the spline used 
  #   to parse the coordinates and possible confidence information
meta_columns:
  - id
  - given names
  - date and time
  - prompt
  - annotation label
  - time in recording
  - number of spline points

# These will be either interleaved or not as specified by 'interleaved coords'.
# Confidence values are always assumed to be non-interleaved.
# Accepted values: 'r' with 'phi', 'x' with 'y', and 'confidence'
data_columns:
  - r
  - phi
  - confidence
