# This tells SATKIT which metadata importer to use.
data_source: AAA

# Strict YAML file specifying recordings to be excluded based 
# on both prompts and file names.
exclusion_list: 

# This is where we read the data and metadata from. Leave the data type specific
# directories empty if everything is in one directory.
data_path: spline_test_token1
wav_directory:
textgrid_directory: 
ultrasound_directory:

# Where to find the spline import data. This is assumed to be relative to data
# path.
spline_import_config: csv_spline_import_config.yaml
