
# Please note that empty file or directory fields are interpreted as not
# available and represented by None. If you want to specify current working
# directory, use '.'

# Default parameters for a data run. Unless you happen to be running example
# tongue data, you should probably change these.
# Plain filename without a directory path will be interpreted as being in
#  the directory of this file.
data_run_parameter_file: patkit-data.yaml

gui_parameter_file: patkit-gui.yaml

publish_parameter_file: patkit-publish.yaml